### ISSUE TITLE
ajax.googleapis.com stop working

### ISSUE THREAD

**Issue by rinkuyadav999** [eyecatchup/SEOstats#100]
ajax.googleapis.com/ajax/services/search/web?v=1.0&q=site:github.com&filter=0

{"responseData": null, "responseDetails": "The Google Web Search API is no longer available. Please migrate to the Google Custom Search API (https://developers.google.com/custom-search/)", "responseStatus": 403}

So how can i use your application ?

**Comment by kapiljindal** [comment]
@ClemensSahs Are you working on this issue?

**Comment by ClemensSahs** [comment]
yes I have a private WIP branch. But in the last week's my job forced much of my time...

this weekend I will have more some time to finish that patch... I hope It will be enough to finish all Unit-Tests

sorry for waiting

**Comment by ClemensSahs** [comment]
So some features on the old API google support not longer without billing API Keys...

I will create some methods:
- nice and sweet methods (you can pay google for access)
- and some bad methods. (with them you must be careful because google will possible ban your IPs)

@kapiljindal
Yes there is a alternative Google Custom Search and many other API google force us to pay

sorry that this issue is so long open

**Comment by kapiljindal** [comment]
@ClemensSahs  thank you for the reply. Could you please tell me the what is the best way to retrieve Google Index count and link count.

Looking forward to your reply.
